import { Error as RevoltError } from "revolt-api";

export enum DiscordErrors {
  UnknownChannel = 10003,
  UnknownGuild = 10004,
  UnknownInvite = 10006,
  UnknownMessage = 10008,
  BotDisallowed = 20001,
  TooManyUsingUsername = 30006,
  TooManyEmoji = 30008,
  TooManyAttachments = 30015,
  InvalidPermissions = 50013,
  AlreadyFriendsError = 80007,
  AutomodInvalidRustServiceResponse = 200002,
}

export enum DiscordErrorMessages {
  AlreadyFriendsError = "You are already friends with that user.",
}

export const BaseTypeRequiredError = {
  code: "BASE_TYPE_REQUIRED",
  message: "This field is required.",
};

export const DiscordErrorMap: Record<RevoltError["type"], DiscordErrors> = {
  AlreadyFriends: DiscordErrors.AlreadyFriendsError,
  LabelMe: DiscordErrors.AlreadyFriendsError,
  AlreadyOnboarded: DiscordErrors.AlreadyFriendsError,
  UsernameTaken: DiscordErrors.TooManyUsingUsername,
  InvalidUsername: DiscordErrors.AlreadyFriendsError,
  UnknownUser: DiscordErrors.AlreadyFriendsError,
  AlreadySentRequest: DiscordErrors.AlreadyFriendsError,
  Blocked: DiscordErrors.AlreadyFriendsError,
  BlockedByOther: DiscordErrors.AlreadyFriendsError,
  NotFriends: DiscordErrors.AlreadyFriendsError,
  UnknownChannel: DiscordErrors.UnknownChannel,
  UnknownAttachment: DiscordErrors.AlreadyFriendsError,
  UnknownMessage: DiscordErrors.UnknownMessage,
  CannotEditMessage: DiscordErrors.AlreadyFriendsError,
  CannotJoinCall: DiscordErrors.AlreadyFriendsError,
  TooManyAttachments: DiscordErrors.TooManyAttachments,
  TooManyReplies: DiscordErrors.AlreadyFriendsError,
  TooManyChannels: DiscordErrors.AlreadyFriendsError,
  EmptyMessage: DiscordErrors.AlreadyFriendsError,
  PayloadTooLarge: DiscordErrors.AlreadyFriendsError,
  CannotRemoveYourself: DiscordErrors.AlreadyFriendsError,
  GroupTooLarge: DiscordErrors.AlreadyFriendsError,
  AlreadyInGroup: DiscordErrors.AlreadyFriendsError,
  NotInGroup: DiscordErrors.AlreadyFriendsError,
  UnknownServer: DiscordErrors.AlreadyFriendsError,
  InvalidRole: DiscordErrors.AlreadyFriendsError,
  Banned: DiscordErrors.AlreadyFriendsError,
  TooManyServers: DiscordErrors.AlreadyFriendsError,
  TooManyEmoji: DiscordErrors.AlreadyFriendsError,
  TooManyRoles: DiscordErrors.AlreadyFriendsError,
  ReachedMaximumBots: DiscordErrors.AlreadyFriendsError,
  IsBot: DiscordErrors.BotDisallowed,
  BotIsPrivate: DiscordErrors.AlreadyFriendsError,
  CannotReportYourself: DiscordErrors.AlreadyFriendsError,
  MissingPermission: DiscordErrors.InvalidPermissions,
  MissingUserPermission: DiscordErrors.InvalidPermissions,
  NotElevated: DiscordErrors.InvalidPermissions,
  NotPrivileged: DiscordErrors.InvalidPermissions,
  CannotGiveMissingPermissions: DiscordErrors.InvalidPermissions,
  NotOwner: DiscordErrors.InvalidPermissions,
  DatabaseError: DiscordErrors.AlreadyFriendsError,
  InternalError: DiscordErrors.AlreadyFriendsError,
  InvalidOperation: DiscordErrors.AlreadyFriendsError,
  InvalidCredentials: DiscordErrors.AlreadyFriendsError,
  InvalidProperty: DiscordErrors.AlreadyFriendsError,
  InvalidSession: DiscordErrors.AlreadyFriendsError,
  DuplicateNonce: DiscordErrors.AlreadyFriendsError,
  VosoUnavailable: DiscordErrors.AlreadyFriendsError,
  NotFound: DiscordErrors.AlreadyFriendsError,
  NoEffect: DiscordErrors.AlreadyFriendsError,
  FailedValidation: DiscordErrors.AlreadyFriendsError,
};
