import { Error as RevoltError } from "revolt-api";

export enum DiscordErrors {
  UnknownChannel = 10003,
  UnknownGuild = 10004,
  UnknownInvite = 10006,
  UnknownMessage = 10008,
  BotDisallowed = 20001,
  TooManyUsingUsername = 30006,
  TooManyEmoji = 30008,
  TooManyAttachments = 30015,
  Unauthorized = 40001,
  InvalidPermissions = 50013,
  AlreadyFriendsError = 80007,
  AutomodInvalidRustServiceResponse = 200002,
}

export const DiscordErrorMessages: Record<DiscordErrors, string> = {
  [DiscordErrors.AlreadyFriendsError]: "You are already friends with that user.",
  [DiscordErrors.UnknownChannel]: "Unknown channel",
  [DiscordErrors.UnknownGuild]: "Unknown guild",
  [DiscordErrors.UnknownInvite]: "Unknown invite",
  [DiscordErrors.UnknownMessage]: "Unknown message",
  [DiscordErrors.BotDisallowed]: "This route cannot be accessed by bots",
  [DiscordErrors.TooManyUsingUsername]: "This username is already taken",
  [DiscordErrors.TooManyEmoji]: "Too many emojis",
  [DiscordErrors.TooManyAttachments]: "Too many attachments",
  [DiscordErrors.Unauthorized]: "Unauthorized",
  [DiscordErrors.InvalidPermissions]: "Invalid permissions",
  [DiscordErrors.AutomodInvalidRustServiceResponse]: "Automod invalid rust service response",
};

export const BaseTypeRequiredError = {
  code: "BASE_TYPE_REQUIRED",
  message: "This field is required.",
};

export const DiscordErrorMap: Record<RevoltError["type"], DiscordErrors> = {
  AlreadyFriends: DiscordErrors.AlreadyFriendsError,
  LabelMe: DiscordErrors.AlreadyFriendsError,
  AlreadyOnboarded: DiscordErrors.AlreadyFriendsError,
  UsernameTaken: DiscordErrors.TooManyUsingUsername,
  InvalidUsername: DiscordErrors.AlreadyFriendsError,
  UnknownUser: DiscordErrors.AlreadyFriendsError,
  AlreadySentRequest: DiscordErrors.AlreadyFriendsError,
  Blocked: DiscordErrors.AlreadyFriendsError,
  BlockedByOther: DiscordErrors.AlreadyFriendsError,
  NotFriends: DiscordErrors.AlreadyFriendsError,
  UnknownChannel: DiscordErrors.UnknownChannel,
  UnknownAttachment: DiscordErrors.AlreadyFriendsError,
  UnknownMessage: DiscordErrors.UnknownMessage,
  CannotEditMessage: DiscordErrors.AlreadyFriendsError,
  CannotJoinCall: DiscordErrors.AlreadyFriendsError,
  TooManyAttachments: DiscordErrors.TooManyAttachments,
  TooManyReplies: DiscordErrors.AlreadyFriendsError,
  TooManyChannels: DiscordErrors.AlreadyFriendsError,
  EmptyMessage: DiscordErrors.AlreadyFriendsError,
  PayloadTooLarge: DiscordErrors.AlreadyFriendsError,
  CannotRemoveYourself: DiscordErrors.AlreadyFriendsError,
  GroupTooLarge: DiscordErrors.AlreadyFriendsError,
  AlreadyInGroup: DiscordErrors.AlreadyFriendsError,
  NotInGroup: DiscordErrors.AlreadyFriendsError,
  UnknownServer: DiscordErrors.AlreadyFriendsError,
  InvalidRole: DiscordErrors.AlreadyFriendsError,
  Banned: DiscordErrors.AlreadyFriendsError,
  TooManyServers: DiscordErrors.AlreadyFriendsError,
  TooManyEmoji: DiscordErrors.TooManyEmoji,
  TooManyRoles: DiscordErrors.AlreadyFriendsError,
  ReachedMaximumBots: DiscordErrors.AlreadyFriendsError,
  IsBot: DiscordErrors.BotDisallowed,
  BotIsPrivate: DiscordErrors.AlreadyFriendsError,
  CannotReportYourself: DiscordErrors.AlreadyFriendsError,
  MissingPermission: DiscordErrors.InvalidPermissions,
  MissingUserPermission: DiscordErrors.InvalidPermissions,
  NotElevated: DiscordErrors.Unauthorized,
  NotPrivileged: DiscordErrors.Unauthorized,
  CannotGiveMissingPermissions: DiscordErrors.InvalidPermissions,
  NotOwner: DiscordErrors.InvalidPermissions,
  DatabaseError: DiscordErrors.AlreadyFriendsError,
  InternalError: DiscordErrors.AlreadyFriendsError,
  InvalidOperation: DiscordErrors.AlreadyFriendsError,
  InvalidCredentials: DiscordErrors.AlreadyFriendsError,
  InvalidProperty: DiscordErrors.AlreadyFriendsError,
  InvalidSession: DiscordErrors.AlreadyFriendsError,
  DuplicateNonce: DiscordErrors.AlreadyFriendsError,
  VosoUnavailable: DiscordErrors.AlreadyFriendsError,
  NotFound: DiscordErrors.AlreadyFriendsError,
  NoEffect: DiscordErrors.AlreadyFriendsError,
  FailedValidation: DiscordErrors.AlreadyFriendsError,
  TooManyEmbeds: DiscordErrors.AlreadyFriendsError,
  DiscriminatorChangeRatelimited: DiscordErrors.AlreadyFriendsError,
};
